// Transaction seed data builders for April and March 2026

export function buildCurrentMonthTransactions(
  userId: string,
  categories: Record<string, string>,
  periodId: string,
  tersoftId: string,
  freelanceId: string,
) {
  return [
    {
      type: 'INCOME' as const,
      amount: BigInt('2500000'),
      description: 'Quincena 1 TerSoft',
      categoryId: categories['Empleo'],
      incomeSourceId: tersoftId,
      date: new Date('2026-04-01'),
      periodId,
      userId,
    },
    {
      type: 'INCOME' as const,
      amount: BigInt('1500000'),
      description: 'Proyecto web freelance',
      categoryId: categories['Freelance'],
      incomeSourceId: freelanceId,
      date: new Date('2026-04-03'),
      periodId,
      userId,
    },
    {
      type: 'EXPENSE' as const,
      amount: BigInt('35000'),
      description: 'Almuerzo restaurante',
      categoryId: categories['Comida'],
      date: new Date('2026-04-01'),
      paymentMethod: 'DEBITO' as const,
      periodId,
      userId,
    },
    {
      type: 'EXPENSE' as const,
      amount: BigInt('120000'),
      description: 'Despensa semanal',
      categoryId: categories['Comida'],
      date: new Date('2026-04-02'),
      paymentMethod: 'DEBITO' as const,
      periodId,
      userId,
    },
    {
      type: 'EXPENSE' as const,
      amount: BigInt('85000'),
      description: 'Recibo CFE',
      categoryId: categories['Servicios'],
      date: new Date('2026-04-01'),
      paymentMethod: 'TRANSFERENCIA' as const,
      periodId,
      userId,
    },
    {
      type: 'EXPENSE' as const,
      amount: BigInt('45000'),
      description: 'Recibo agua',
      categoryId: categories['Servicios'],
      date: new Date('2026-04-02'),
      paymentMethod: 'TRANSFERENCIA' as const,
      periodId,
      userId,
    },
    {
      type: 'EXPENSE' as const,
      amount: BigInt('25000'),
      description: 'Boletos cine',
      categoryId: categories['Entretenimiento'],
      date: new Date('2026-04-02'),
      paymentMethod: 'CREDITO' as const,
      periodId,
      userId,
    },
    {
      type: 'EXPENSE' as const,
      amount: BigInt('17900'),
      description: 'Netflix mensual',
      categoryId: categories['Suscripciones'],
      date: new Date('2026-04-01'),
      paymentMethod: 'CREDITO' as const,
      periodId,
      userId,
    },
    {
      type: 'EXPENSE' as const,
      amount: BigInt('9900'),
      description: 'Spotify mensual',
      categoryId: categories['Suscripciones'],
      date: new Date('2026-04-01'),
      paymentMethod: 'CREDITO' as const,
      periodId,
      userId,
    },
    {
      type: 'EXPENSE' as const,
      amount: BigInt('50000'),
      description: 'Gasolina',
      categoryId: categories['Transporte'],
      date: new Date('2026-04-01'),
      paymentMethod: 'DEBITO' as const,
      periodId,
      userId,
    },
    {
      type: 'EXPENSE' as const,
      amount: BigInt('15000'),
      description: 'Uber al centro',
      categoryId: categories['Transporte'],
      date: new Date('2026-04-03'),
      paymentMethod: 'EFECTIVO' as const,
      periodId,
      userId,
    },
    {
      type: 'EXPENSE' as const,
      amount: BigInt('35000'),
      description: 'Corte de pelo',
      categoryId: categories['Otros'],
      date: new Date('2026-04-02'),
      paymentMethod: 'EFECTIVO' as const,
      periodId,
      userId,
    },
    {
      type: 'EXPENSE' as const,
      amount: BigInt('75000'),
      description: 'Pago minimo Tarjeta Nu',
      categoryId: categories['Otros'],
      date: new Date('2026-04-03'),
      paymentMethod: 'TRANSFERENCIA' as const,
      notes: 'Pago de deuda',
      periodId,
      userId,
    },
  ]
}

export function buildPreviousMonthTransactions(
  userId: string,
  categories: Record<string, string>,
  periodId: string,
  tersoftId: string,
) {
  return [
    {
      type: 'INCOME' as const,
      amount: BigInt('2500000'),
      description: 'Quincena 1 TerSoft',
      categoryId: categories['Empleo'],
      incomeSourceId: tersoftId,
      date: new Date('2026-03-01'),
      periodId,
      userId,
    },
    {
      type: 'INCOME' as const,
      amount: BigInt('2500000'),
      description: 'Quincena 2 TerSoft',
      categoryId: categories['Empleo'],
      incomeSourceId: tersoftId,
      date: new Date('2026-03-15'),
      periodId,
      userId,
    },
    {
      type: 'EXPENSE' as const,
      amount: BigInt('180000'),
      description: 'Despensa quincenal',
      categoryId: categories['Comida'],
      date: new Date('2026-03-02'),
      paymentMethod: 'DEBITO' as const,
      periodId,
      userId,
    },
    {
      type: 'EXPENSE' as const,
      amount: BigInt('95000'),
      description: 'Recibo CFE marzo',
      categoryId: categories['Servicios'],
      date: new Date('2026-03-05'),
      paymentMethod: 'TRANSFERENCIA' as const,
      periodId,
      userId,
    },
    {
      type: 'EXPENSE' as const,
      amount: BigInt('60000'),
      description: 'Salida fin de semana',
      categoryId: categories['Entretenimiento'],
      date: new Date('2026-03-08'),
      paymentMethod: 'CREDITO' as const,
      periodId,
      userId,
    },
    {
      type: 'EXPENSE' as const,
      amount: BigInt('27800'),
      description: 'Suscripciones digitales',
      categoryId: categories['Suscripciones'],
      date: new Date('2026-03-01'),
      paymentMethod: 'CREDITO' as const,
      periodId,
      userId,
    },
    {
      type: 'EXPENSE' as const,
      amount: BigInt('70000'),
      description: 'Gasolina y casetas',
      categoryId: categories['Transporte'],
      date: new Date('2026-03-10'),
      paymentMethod: 'DEBITO' as const,
      periodId,
      userId,
    },
    {
      type: 'EXPENSE' as const,
      amount: BigInt('350000'),
      description: 'Mensualidad prestamo personal',
      categoryId: categories['Otros'],
      date: new Date('2026-03-15'),
      paymentMethod: 'TRANSFERENCIA' as const,
      notes: 'Pago de deuda',
      periodId,
      userId,
    },
    {
      type: 'EXPENSE' as const,
      amount: BigInt('75000'),
      description: 'Pago minimo Tarjeta Nu',
      categoryId: categories['Otros'],
      date: new Date('2026-03-05'),
      paymentMethod: 'TRANSFERENCIA' as const,
      notes: 'Pago de deuda',
      periodId,
      userId,
    },
  ]
}
